### ISSUE TITLE
Ember 2

### ISSUE THREAD

**Issue by KennedyTedesco** [pzuraq/liquid-tether#20]
First of all I have to say that this is an amazing addon. Can I ask you if you have any plans to support Ember 2?

Cheers!

**Comment by pzuraq** [comment]
Thanks! Glad you're liking it :smile: 

Currently the tests are passing on all versions of Ember >= 1.13.8, which should include 2.0 and 2.1. I haven't personally tested it out much there, but we will be moving our apps over shortly so I should be on that. Are you encountering any bugs or issues with it?

**Comment by KennedyTedesco** [comment]
Yes, a few issues:

> DEPRECATION: Using `ApplicationInstance.container.lookup` is deprecated. Please use `ApplicationInstance.lookup` instead. [deprecation id: ember-application.app-instance-container] See http://emberjs.com/deprecations/v2.x/#toc_ember-applicationinstance-container for more details.

And because of that (I guess) i'm having this one:

> Uncaught Error: Assertion Failed: A helper named 'liquid-versions' could not be found

But, nevermind, it's good to know you'll be on that soon. :smile: 

I'm closing for now. Thanks!

**Comment by pzuraq** [comment]
Definitely an issue! I'll get on this asap, let you know when I make some progress.

**Comment by KennedyTedesco** [comment]
Awesome! Thank you.

**Comment by ehariprasad** [comment]
Hi,

Am also trying to use it with Ember 2.0 and facing same issue.

Any Updates ?

Thanks,

**Comment by pzuraq** [comment]
@KennedyTedesco @ehariprasad the issue regarding the instance initializer was solved a while back. If you are using a pre-2.0 version of Ember, you'll still see that deprecation warning because we have to use the old `ApplicationInstance.container.lookup` method unless the new one exists. If you're trying to upgrade you should be in the clear.

As for the `liquid-versions` issue, have you installed liquid-fire? It is a dependency for liquid-tether, and currently there isn't a blueprint to add it.

**Comment by ehariprasad** [comment]
Thanks @pzuraq its working like a charm after installing liquid-fire v-0.21.2.

**Comment by KennedyTedesco** [comment]
Like a charm here :heart:
