### ISSUE TITLE
outlet in modal

### ISSUE THREAD

**Issue by BenjaminHorn** [pzuraq/liquid-tether#55]
I have a list view with an outlet in the route _/partners_. If one of the items is clicked it routes to eg.  _/partners/1_, which is a liquid tether modal. In the modal I have a tab, with some routes and an outlet. If I route to _/partners/1/addresses_, I can see the **addresses.hbs** in the modal's outlet **and** the _/partners_'s outlet too. Obviously I want to see the content **only** in the modal.

**Comment by pzuraq** [comment]
This one's going to be pretty nasty I bet...

Can you tell me what versions of Ember and Ember CLI you're on? One simple thing we can do is make sure we hide the original outlet using CSS, but then we're attaching the DOM nodes there so that's probably a performance concern. For now we'll go with the hiding strategy and start looking into why exactly Ember is rendering in two spots instead of just one.

**Comment by BenjaminHorn** [comment]
Ember      : 2.4.5
Ember CLI: 2.3.0

I managed to hide it with CSS, and it works for now, but it would be nice to have a better solution.

**Comment by pzuraq** [comment]
@BenjaminHorn I am unable to reproduce this problem in the Liquid Tether demo pages, check out this branch to see the test scenario I tried to setup for it: https://github.com/pzuraq/liquid-tether/tree/nested-route-duplication-bug

Can you submit an example of the problem in action? If not I'm going to have to close this issue for now.

**Comment by BenjaminHorn** [comment]
It is gone now. Probably it was a bug at **my** side.
