### ISSUE TITLE
Acceptance test following integration test

### ISSUE THREAD

**Issue by snewcomer** [pzuraq/liquid-tether#59]
`.liquid-target-container` from liquid-wormhole class is present in an integration test after acceptance test runs.  If the other way around, it isn't present.  Thus the context of `this` in the integration test is the above and not the application and results in failing tests.  

Lmk if you want an integration test as well to play with and I can get it up here.

![screen shot 2016-08-11 at 7 27 56 pm](https://cloud.githubusercontent.com/assets/7374640/17611173/bdd0dee2-5ff9-11e6-8849-28936f719a38.png)

**Comment by pzuraq** [comment]
hmm, interesting. There's some cleanup that must be getting done in integration tests that isn't happening in acceptance tests. I'll take a look, an example integration test would be really helpful.

**Comment by kylemellander** [comment]
I'm also experiencing this issue.  Spent a lot of time tracking this down :)

**Comment by snewcomer** [comment]
@pzuraq Noticing that `.liquid-target-container` is gone when I add an integration test to the dummy app. There is probably some differences from our app to this simple dummy app setup that I am missing.  Any thoughts?

**Comment by kylemellander** [comment]
I believe that the integration tests tear down the `rootElement` correctly, but the acceptance tests don't.  We have an issue where always the first integration test that runs after acceptance tests fail (showing that the acceptance test isn't tearing down). 

I have thrown a debugger in before the first integration spec runs and after a bunch of acceptance tests and we have about 15 empty liquid-target-containers.

**Comment by pzuraq** [comment]
Tracked down the issue, it has to do with the fact that the `liquid-target-container` is appended outside of the scope of the application. I think this and pzuraq/liquid-wormhole#6 make a strong argument for attaching the container to the application's element instead of rootElement, but I think that'll require a major version revision (theoretically this could affect the positioning and styles of tethers). I'm going to start working on it and the rest of the issues, see if I can't knock them all out at once.

**Comment by pzuraq** [comment]
@snewcomer @kylemellander Ok, beta 2 is out now and the new docs are up! This issue should be fixed there, let me know if you have any feedback or questions. I'll close this once v2.0.0 is released.
